-- function ColorMyPencils(color)
-- 	color = color or "rose-pine"
-- 	vim.cmd.colorscheme(color)
--
-- 	vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
--
-- 	-- Telescope transparency
-- 	vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { bg = "none" })
--
-- end
--
-- return {
--     {
--         "folke/tokyonight.nvim",
--         config = function()
--             require("tokyonight").setup({
--                 -- your configuration comes here
--                 -- or leave it empty to use the default settings
--                 style = "storm", -- The theme comes in three styles, `storm`, `moon`, a darker variant `night` and `day`
--                 transparent = true, -- Enable this to disable setting the background color
--                 terminal_colors = true, -- Configure the colors used when opening a `:terminal` in Neovim
--                 styles = {
--                     -- Style to be applied to different syntax groups
--                     -- Value is any valid attr-list value for `:help nvim_set_hl`
--                     comments = { italic = false },
--                     keywords = { italic = false },
--                     -- Background styles. Can be "dark", "transparent" or "normal"
--                     sidebars = "dark", -- style for sidebars, see below
--                     floats = "dark", -- style for floating windows
--                 },
--             })
--         end
--     },
--
--
--       {
--         "rose-pine/neovim",
--         name = "rose-pine",
--         config = function()
--             require('rose-pine').setup({
--                 disable_background = true,
--                 disable_float_background = true,
--             })
--         end
--     },
--     {
--         dir = "~/.config/nvim/lua/matthew/lazy/",
--         name = "artix-ice",
--         config = function()
--             require('matthew.lazy.artix-ice').setup()
--         end
--     },
-- }

return {}



